In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()


In [4]:
#print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
y = iris.target

In [7]:
#class 0 -->[1,0,0] one hot encoding
#class 1 -->[0,1,0]

In [8]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [10]:
y = to_categorical(y)

In [9]:
y.shape
X.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [13]:
y#one hot encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.3 , random_state = 42)

In [16]:
from sklearn.preprocessing import MinMaxScaler# it fits between 0 and 1 divides by max number

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scalar_X_train = scaler_object.transform(X_train)
scalar_x_test = scaler_object.transform(X_test)

In [20]:
from keras.models import Sequential 
from keras.layers import Dense

In [21]:
model = Sequential()

In [22]:
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [23]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(scalar_X_train,Y_train, epochs = 150,verbose = 2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 0s - loss: 1.2055 - acc: 0.2952
Epoch 2/150
 - 0s - loss: 1.1862 - acc: 0.2952
Epoch 3/150
 - 0s - loss: 1.1695 - acc: 0.2952
Epoch 4/150
 - 0s - loss: 1.1549 - acc: 0.2952
Epoch 5/150
 - 0s - loss: 1.1416 - acc: 0.2952
Epoch 6/150
 - 0s - loss: 1.1296 - acc: 0.2952
Epoch 7/150
 - 0s - loss: 1.1174 - acc: 0.2952
Epoch 8/150
 - 0s - loss: 1.1067 - acc: 0.2857
Epoch 9/150
 - 0s - loss: 1.0960 - acc: 0.2857
Epoch 10/150
 - 0s - loss: 1.0863 - acc: 0.2857
Epoch 11/150
 - 0s - loss: 1.0763 - acc: 0.2952
Epoch 12/150
 - 0s - loss: 1.0674 - acc: 0.3143
Epoch 13/150
 - 0s - loss: 1.0592 - acc: 0.4476
Epoch 14/150
 - 0s - loss: 1.0515 - acc: 0.5619
Epoch 15/150
 - 0s - loss: 1.0445 - acc: 0.6190
Epoch 16/150
 - 0s - loss: 1.0380 - acc: 0.6381
Epoch 17/150
 - 0s - loss: 1.0321 - acc: 0.6381
Epoch 18/150
 - 0s - loss: 1.0258 - acc: 0.6381
Epoch 19/150
 - 0s - loss: 1.0199 - acc: 0.6381
Epoch 20/150
 - 0s - loss: 1.0137 - acc: 0.6381
E

In [28]:
model.predict_classes(scalar_x_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [30]:
predictions = model.predict_classes(scalar_x_test)

In [33]:
Y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [35]:
print(accuracy_score(Y_test.argmax(axis = 1),predictions))

0.9555555555555556


In [37]:
# saving and loading back model
model.save('model.h5')


In [39]:
from keras.models import load_model
new_model = load_model('model.h5')